# Generated by Django 3.0.5 on 2020-09-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200910_0930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterPeople',
        ),
        migrations.AlterModelOptions(
            name='tasko',
            options={},
        ),
        migrations.AddField(
            model_name='tasko',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tasko',
            name='description',
            field=models.TextField(null=True, verbose_name='Описания задания'),
        ),
        migrations.AddField(
            model_name='tasko',
            name='price',
            field=models.CharField(max_length=50, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tasko',
            name='task',
            field=models.CharField(max_length=90, verbose_name='Вид поездки'),
        ),
    ]
