# Generated by Django 3.0.5 on 2020-09-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200916_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasko',
            name='image',
            field=models.ImageField(null=True, upload_to='image/BD/'),
        ),
    ]
