# Generated by Django 3.0.5 on 2020-09-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tasko_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasko',
            name='stars',
            field=models.CharField(choices=[('1', '1 звезда'), ('2', '2 звезды'), ('3', '3 звезды'), ('4', '4 звезды'), ('5', '4 звезды')], max_length=2, null=True, verbose_name='Количевство звезд отеля'),
        ),
        migrations.AlterField(
            model_name='tasko',
            name='image',
            field=models.ImageField(null=True, upload_to='BD/'),
        ),
    ]
