# Generated by Django 3.0.5 on 2020-09-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200919_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasko',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tasko',
            name='stars',
            field=models.CharField(choices=[('1', '1 звезда'), ('2', '2 звезды'), ('3', '3 звезды'), ('4', '4 звезды'), ('5', '5 звезд')], max_length=2, null=True, verbose_name='Количевство звезд отеля'),
        ),
        migrations.AlterField(
            model_name='tasko',
            name='title',
            field=models.CharField(max_length=28, verbose_name='Название'),
        ),
    ]
